### ISSUE TITLE
Changes made to waveparam.txt not applied 

### ISSUE THREAD

**Issue by BaltazaR4** [Princess-of-Sleeping/psp2wpp#1]
Hello there. 

After editing and reloading the waveparam.txt many times with the reload app, the changes made to the txt file are not apllied to the waves, leaving you no other option but uninstalling the plug and rebooting the ps vita.

Thanks in advance.

**Comment by Princess-of-Sleeping** [comment]
To reload a custom wave param, you need to move to a page that doesn't have the custom wave param applied after launching the reload app.

**Comment by Princess-of-Sleeping** [comment]
This has been fixed in psp2wpp v1.1.1, waveparam now automatically updates after psp2wpp-reload without page navigation.
