### ISSUE TITLE
Can't make it work and can't recover the original vita waves after uninstall

### ISSUE THREAD

**Issue by KaleBellota** [Princess-of-Sleeping/psp2wpp#2]
Hello I can't make it work, after try everything I uninstalled the plugin but now I can't recover the original vita waves. Please can someone tell me how to make it work and how recover the original vita waves? Thanks

**Comment by KaleBellota** [comment]
I found the issue, it seems that can´t work together with the plugin Autoboot

**Comment by Princess-of-Sleeping** [comment]
Deleting psp2wpp.suprx and waveparam.bin/waveparam.txt should bring it back. Also don't forget to select another wave with the shell's wave select. If psp2wpp is not loaded the vita will show the default wave.
