### ISSUE TITLE
Question for about more custom waves

### ISSUE THREAD

**Issue by Havocking1992** [Princess-of-Sleeping/psp2wpp#3]
> The wave param list is statically placed in the SceShell data segment and currently only one is available. This plugin makes use of that space. A simple workaround is to overwrite the SCE original waveparams.

Can you clarify how this is done? Does it mean that i can rewrite EVERY Vita original Wave? I have bunch of cool looking mutated waves and i want to use them. Can you please explain how to do it?

I love this plugin so much, it does have future, just letting you know :)

**Comment by Princess-of-Sleeping** [comment]
yes. All original waves can be overwritten. I also completed a method for that, but it requires a patch for each fw.
I plan to commit the code after adding the fw offsets for major versions.

**Comment by Havocking1992** [comment]
That's amazing!

**Comment by Princess-of-Sleeping** [comment]
It's was released as pre-release. https://github.com/Princess-of-Sleeping/psp2wpp/releases/tag/v1.1

Copy the txt with the name in [list](https://github.com/Princess-of-Sleeping/psp2wpp/tree/master/color/list) to the same place as waveparam.txt, or rename your waveparam to the name in [list](https://github.com/Princess-of-Sleeping/psp2wpp/tree/master/color/list) and copy it to the same place as waveparam.txt. and report the results.

effects_original_01 is already implemented as the main feature of psp2wpp, so we don't need it here.

Also, sorting when wave select in shell is as follows.
```
	effects_original_01 (this SceReserved wave. also psp2wpp use area)
	effects_default_0512_01
	iboot
	effects_0406_ruby
	effects_0407_purple_01
	effects_0408_01_orange
	effects_0411_purple_02
	effects_0415_A5
	effects_0518_dalia
	effects_0518_gray_FLAT
	effects_0518_ruby
	effects_A1
	effects_black
	effects_blue_FLAT
	effects_blueTB_0513_01
	effects_bluewhite_05
	effects_casis
	effects_green_0512_01
	effects_koiao_0512_01
	effects_maintosh
	effects_marrygold
	effects_peach_0512_001
	effects_purple_01
	effects_purplered
	effects_yellow_0512_01
	effects_redTB_0513_01
	effects_limegreen_0513_02
	effects_turquoise_0513_01
	effects_color_vari_2g_01
	effects_color_vari_2g_02
	effects_color_vari_2g_03
	effects_color_vari_2g_04
```

**Comment by Havocking1992** [comment]
Results: It still works only as v1.0 (waveparam.txt + waveparam.bin)
Things i've tried:
1) "iboot.txt" - does nothing
2) "effects_default_0512_01.txt" - does nothing
3) "effects_default_0512_01.txt" + "waveparam.txt" - does nothing
4) "effects_default_0512_01.txt" + "waveparam.txt" + "waveparam.bin" - works, but shows only "waveparam" wave
5) "effects_default_0512_01.txt" + "effects_default_0512_01.bin" + "waveparam.txt" + "waveparam.bin" - works, but shows only "waveparam" wave

I have tried everytime other waves (in case if it targets differene wave) and yes, switching to screen with different wave and back.

By the way when launched "psp2wpp-reload" vita freezes on black screen and Vita shuts off after while, so i've restarted Vita instead every single time i did change to files.

**Comment by Princess-of-Sleeping** [comment]
Naming works with "waveparam_effects_default_0512_01.txt" but freezing is obviously a bug... ~~need fixing it~~

**Comment by Princess-of-Sleeping** [comment]
@Havocking1992 Is your vita on 3.65 HENkaku ensõ?

**Comment by Havocking1992** [comment]
3.60 HENkaku ensõ

**Comment by Havocking1992** [comment]
I tried renaming wave to "waveparam_effects_default_0512_01.txt", restarted system and it does not work too.

**Comment by Havocking1992** [comment]
Okay finally got it working, i've just totally misunderstood your directions. Now i have "waveparam.bin", "waveparam_effects_default_0512_01.txt" and "waveparam_iboot.txt" in "data" folder, and first two waves are my custom ones! Thank you!

**Comment by Havocking1992** [comment]
By the way, "psp2wpp-reload" crashes when is "waveparam.txt" present in "data" folder.

**Comment by Princess-of-Sleeping** [comment]
Thank you for the detailed information. There is something that fixes them, so please test them with waveparam.txt
[psp2wpp.zip](https://github.com/Princess-of-Sleeping/psp2wpp/files/11009506/psp2wpp.zip)

**Comment by Havocking1992** [comment]
You're welcome.

I tried the plugin you sent and everything works as it should.

I have a small suggestion for improvement: if it would be possible for the plugin to take waveparams from a subfolder (probably "ux0:data/waveparams/") and for the waveparams names to be simplified (0.txt, 1.txt, 2.txt, 3.txt. ....).

**Comment by Princess-of-Sleeping** [comment]
Thank you for testting.
And the subfolder tests are in the plugin below.
[psp2wpp.zip](https://github.com/Princess-of-Sleeping/psp2wpp/files/11009619/psp2wpp.zip)

`ux0:data/waveparams/%d.txt`. %d is from 0 to 30.

**Comment by Havocking1992** [comment]
Here is one of my waveparams [https://webshare.cz/#/file/dJxToJlJBo/waveparam-txt](https://webshare.cz/#/file/dJxToJlJBo/waveparam-txt)

**Comment by Princess-of-Sleeping** [comment]
Surprisingly I like that wave. Well, I waiting for the report of subfolder.

**Comment by Havocking1992** [comment]
I have just ended testing it and it works perfectly. Thank you !

**Comment by Princess-of-Sleeping** [comment]
You are welcome.

**Comment by Havocking1992** [comment]
Sorry to interrupt after closing issue, but I was just adding more waveparams to the plugin, and I find that some of them are mis-referencing. I thoroughly tested it, and I am sending the result: [https://webshare.cz/#/file/IuGAK21Vhp/test-waveparams2-bmp](https://webshare.cz/#/file/IuGAK21Vhp/test-waveparams2-bmp)

**Comment by Princess-of-Sleeping** [comment]
Do some of your waveparams have unfilled values?
like:
```
type Material
# not used. so comment out
# set_value color.r           0.321427
# set_value color.g           0.383927
# set_value color.b           0.446427
# set_value color.a           1.000000
set_value diffuse_coeff     0.491071
set_value specular_coeff    1.525877
```

**Comment by Havocking1992** [comment]
None of them are commented out, they are almost identical as the one i've sent you and I haven't deleted any values.

One of them have comments after the values like this:
`set_value specular_coeff 1.0 #unknown`

and that wave is working without problems.

**Comment by Princess-of-Sleeping** [comment]
Try this one.
[psp2wpp.zip](https://github.com/Princess-of-Sleeping/psp2wpp/files/11019841/psp2wpp.zip)

**Comment by Havocking1992** [comment]
I've tried 8 waves, "0.txt" to "6.txt" is ok, but "7.txt" (which should be dark-blue) is now found on fourth wave from end (yellow-ish color), in older .suprx it was on fifth wave from end (light blue color)

**Comment by Princess-of-Sleeping** [comment]
Sorry, the value was off by one.
[psp2wpp.zip](https://github.com/Princess-of-Sleeping/psp2wpp/files/11020096/psp2wpp.zip)

**Comment by Havocking1992** [comment]
It is ok, we are slowly getting there :)
"7.txt" is now present on 26th wave (torquise color), but it should be on dark-blue color, which is 9th wave.

**Comment by Princess-of-Sleeping** [comment]
This is should work now.
[psp2wpp.zip](https://github.com/Princess-of-Sleeping/psp2wpp/files/11020811/psp2wpp.zip)

**Comment by Havocking1992** [comment]
Yes, it works. I will test other 24 waves, i'll report back after while.

**Comment by Havocking1992** [comment]
All the way from "0.txt" to "30.txt" it works as supposed to. Thank you very much!

By the way when i rename/delete ".txt"
file and launch "psp2wpp-reload", it does not refresh corresponding wave to default one, until vita restarts.

I have little question; wave icons in "select window" can be changed so they match reality? If yes then please how to do that?

**Comment by Princess-of-Sleeping** [comment]
The default waveparam is literally overwritten, so it stays there until you reboot.

There is already a select window color change, but this would require an offset per fw. Please wait a moment to add them.

https://github.com/Princess-of-Sleeping/psp2wpp/blob/12ac51384ce6392b9a1bc4fc865959580b32a99f/src/main.c#L51-L59

**Comment by Havocking1992** [comment]
Allright, thank you.

**Comment by Princess-of-Sleeping** [comment]
We have released [v1.1.2](https://github.com/Princess-of-Sleeping/psp2wpp/releases/tag/v1.1.2) with these fixes. And if you want to apply a color to the select add the following parameter to your waveparam.txt.

If you have any problems, open iusse again. Thank you.

```
type Select
set_value selecter[0].r           0.500000
set_value selecter[0].g           0.000000
set_value selecter[0].b           0.000000
set_value selecter[0].a           1.000000
set_value selecter[1].r           0.9
set_value selecter[1].g           0.2
set_value selecter[1].b           0.1
set_value selecter[1].a           1.000000
```

**Comment by Havocking1992** [comment]
i've discovered that those parameters does not work in "waveparam.txt", but they work in other waves. But they work half-way somewhat. selecter[0] changes bottom line with according color, but selecter[1] seems to have twisted values. If i set selecter[1].r, selecter[1].g, selecter[1].b all to 1, i see torquise color

**Comment by Havocking1992** [comment]
*i see torquise color on top, instead of white. Sorry, message got sent before i ended it.

**Comment by Princess-of-Sleeping** [comment]
Thanks again for finding the bug. It seems the value of select[1].r is not applied.
Wrong reference indeed.
https://github.com/Princess-of-Sleeping/psp2wpp/blob/3506d6daebc2f6ab22a90ce82cca5b7c19b67c84/src/wave_config.c#L41-L44

I will soon release v1.1.3 with this fixed.

**Comment by Princess-of-Sleeping** [comment]
Also for now select colors in waveparam.txt is only read at boot up.

**Comment by Havocking1992** [comment]
selecter colors in "waveparam.txt" still doesn't work, i've restarted vita multiple times.

selecter in other waves works.

**Comment by Princess-of-Sleeping** [comment]
We have released [psp2wpp v1.1.4](https://github.com/Princess-of-Sleeping/psp2wpp/releases/tag/v1.1.4) which fixes that bug. In v1.1.3, the contents of waveparam.bin were applied.

**Comment by Havocking1992** [comment]
It works! Thank you!

**Comment by Princess-of-Sleeping** [comment]
you are welcome. And Thank you.
